version: '3.7'
services:
  backend:
    build: .
    container_name: backend-api
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - backend-postgres
      - backend-redis
    networks:
      - bridge-network
  backend-postgres:
    image: postgres
    restart: always
    container_name: backend-postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bridge-network
  backend-redis:
    image: redis
    restart: always
    container_name: backend-redis
    ports:
      - 6379:6379
    networks:
      - bridge-network
volumes:
  db-data:
networks:
  bridge-network:
    driver: bridge
