version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '54321:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '63791:6379'
volumes:
  db-data:
